export enum userActionTypes {
  SET_CURRENT_USER_REQUEST = 'SET_CURRENT_USER_REQUEST',
  SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE',
}
