projects:
  twitterclone:
    schemaPath: src/graphql/schema.json
    includes:
      - graphl/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: API.ts
        docsFilePath: graphl
